title: Mustafa Hussein
#logo: /assets/img/headshot_circle.png
#description: IT Project Manager
#show_downloads: true
theme: jekyll-theme-cayman

author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Mustafa Hussein"
  pronouns         : # example: "she/her"  
  bio              : #"Short biography for the left-hand sidebar"
  location         : "United Kingdom"
  employer         : "University of Essex"
  uri              : # URL
  email            : "husseinmustafa12@yahoo.com" 
